# Generated by Django 2.2.1 on 2019-06-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_accomplishment_entrepreneur_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrepreneur',
            name='portfolio',
            field=models.ManyToManyField(blank=True, to='users.Portfolio'),
        ),
    ]
