# Generated by Django 2.2.1 on 2019-06-23 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('users', '0004_auto_20190623_1545'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EntrepreneurProfile',
            new_name='Entrepreneur',
        ),
    ]
