# Generated by Django 2.2.1 on 2019-06-30 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190623_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrepreneur',
            name='accomplishnment',
        ),
        migrations.RemoveField(
            model_name='entrepreneur',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='entrepreneur',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='entrepreneur',
            name='user',
        ),
        migrations.DeleteModel(
            name='Accomplishment',
        ),
        migrations.DeleteModel(
            name='Entrepreneur',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
