# Generated by Django 2.2.1 on 2019-08-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pitch'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='offer_status',
            field=models.CharField(choices=[('Negotiable', 'Negotiable'), ('Non-Negotiable', 'Non-Negotiable')], default='negotiable', max_length=20),
            preserve_default=False,
        ),
    ]
