# Generated by Django 2.2.1 on 2019-08-22 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pitch_offer_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pitch',
            name='skills',
        ),
        migrations.AddField(
            model_name='pitch',
            name='skills',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
